name: Scheduled Task

on:
  schedule:
    - cron: '30 5 * * 1' # Кожного понеділка о 5:30 ранку
  workflow_dispatch: # Дозволяє запускати вручну через інтерфейс GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Parse Script
        run: |
          session_token="${{ secrets.OAUTH_TOKEN }}"
          echo "Using session token: $session_token"
          response=$(curl -H "Authorization: Bearer $session_token" -X GET https://installsat.fun/guru/parse/trans-news)
          echo "Server Response: $response"
          if [[ "$response" == *"login?callbackUrl"* ]]; then
            echo "Authentication failed. Redirected to login page."
            exit 1
          fi
