export const initChannel = {
  id: -1,
  title: '',
  cpu: '',
  compress: '',
  logo: '',
  description: '',
  text: '',
  tema: '',
  cat: '',
  frequency: '',
  sat: '',
  beam: '',
  encryption: '',
  lang: '',
  view: '',
  url: '',
  canonical: '',
  programma: '',
  potok: '',
  pars_uppod: '',
  pattern: '',
  tvforsite_net: '',
  simpletv: '',
  jwplayer: '',
  tvforsite_ru: '',
  other_stream: '',
  mark: '',
  aspect: '',
  biss: '',
  country_id: '',
  ip_deny: '',
  telegid_id: '',
  vipiko: '',
  vsetv: '',
  no_googlads: '',
};

export type TChannel = typeof initChannel;
